//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        public int AppartmentId { get; set; }
        public int NumberOfRoom { get; set; }
        public int NumberOfBath { get; set; }
        public int NumberOfParking { get; set; }
        public int FloorNum { get; set; }
        public int PricePerMonth { get; set; }
        public string Description { get; set; }
        public string RentStatus { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
