//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public System.DateTime Schedule { get; set; }
        public string Location { get; set; }
        public string AttendingPerson { get; set; }
        public int TenantId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
